### ISSUE TITLE
Storing auth cookie on browser

### ISSUE THREAD

**Issue by mahirk** [vardhman1996/tractionuw#5]
Everytime I close the page, I end up logging out (not sure if its because its hosting) but a suggestion would be to store the auth token in a cookie so that everytime I go back I am logged in?

**Comment by danfang** [comment]
Interesting - does that happen consistently? Tested on Chrome, it seems to last the entire session (basically no expiration date). We're using node session middleware (express-session), so maybe there are some custom fields to explicitly set cookie expiration. Let me know if you can get this to happen consistently, and if so, what browser you're on.

It could also just be me restarting the server. Right now I think it uses in-memory session storage, which we'll be shifting to redis for production.
